// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "OPDS Client",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "OPDS Client",
            targets: ["AppModule"],
            teamIdentifier: "2D7T23VV7R",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .localNetwork(purposeString: "Finding local OPDS servers", bonjourServiceTypes: ["_calibre._tcp.", ""])
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", "5.0.0"..<"6.0.0"),
        .package(url: "https://github.com/MaxDesiatov/XMLCoder.git", "0.9.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Alamofire", package: "alamofire"),
                .product(name: "XMLCoder", package: "xmlcoder")
            ],
            path: "."
        )
    ]
)
